### ISSUE TITLE
pytest actions somehow use wrong version of python

### ISSUE THREAD

**Issue by domi119017** [domi119017/prynterface#34]

**Comment by domi119017** [comment]
Possibly because of caching?
```
      - name: Cache the virtualenv
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
```
